# Generated by Django 3.0.2 on 2020-03-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trendingtopics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treding_topics', models.TextField()),
            ],
        ),
    ]
