# Generated by Django 3.0.2 on 2020-03-01 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine_app', '0002_trendingtopics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trendingtopics',
            old_name='treding_topics',
            new_name='trending_topics',
        ),
    ]
